#ifndef GRAPHICS_HPP
#define GRAPHICS_HPP

// File to keep this file
#include "Types.hpp"
#ifdef RPI
#include "../States.hpp"
#endif

/**
 *
 * @class SDLManager
 *
 * @brief SDL Library wrapper for image rendering.
 *
 * @returns
 * A Window manager that frees memory when they reach out of scope.
 *
 * @details
 * Class that wraps simple SDL functions to create different textures for
 * rendering.
 */
class SDLManager {

public:
  /**
   * @brief Constructor that initializes the SDL window.
   *
   * Initializes memory needed and creates standardized window and renderer.
   *
   * @param windowTitle Name of the SDL Window
   */
  SDLManager(const std::string &windowTitle);

  /**
   * @brief Destructor for freeing memory and exiting the application
   */
  ~SDLManager();

#ifdef RPI
  /**
   * @brief Polls PinState
   *
   * Check for changes on GPIO pins and applies them to internal bools,
   * for manipulating certain states.
   */
  void poll(const PinState &state, bool paymentStatus);
#endif

  /**
   * @brief Sets up the surface and window specifications
   */
  void setup();

  /**
   * @brief Rendering function.
   *
   * Called at the end of main to present the result of values genereted.
   *
   * @param weight actual weight that gets presented on application.
   * @param clock actual date and time presented by device
   */
  void render(int weight, std::string_view clock);

  /**
   * @brief Checks the status of member variable status.
   *
   * @return state of SDL Window.
   */
  bool getStatus();

  /**
   * @brief Event poller for desktop application.
   *
   * Polls event queue used for testing certain functionalities.
   */
  void pollEvents();

private:
  enum class SurfaceState : uint8_t {
    WELCOME_MESSAGE,
    QR,
    WEIGHT,
    PROCESSING_PAYMENT
  } Surface;

  /**
   * @brief Helper function for SDL errors.
   *
   * @param errMsg message generated from SDL_GetError().
   */
  void printErrMsg(const std::string &errMsg);

  /**
   * @brief Creates the texture from the provided surfaces.
   */
  void createTextures(const std::string &logoPath, const std::string &qrPath,
                      const std::string &fontPath);

  /**
   * @brief Loads the specified IMG (.png) used for rendereing.
   */
  void loadSurfaceOfIMG(const std::string &filepath);

  /**
   * @brief Loads the specified TTF (.ttf) used for rendering.
   *
   * Sets the pixel depth to 400 and creates the surface needer for weight
   * texture.
   *
   * @param filepath file path to the font (.ttf).
   * @param startWeight weight to start with set to 0.
   */
  void loadFontSurface(const std::string &filepath);

  /**
   * @brief A constructor for the Welcome Message.
   *
   * @param messages
   * Load the litreals into memory
   */
  void createMessages(const std::vector<std::string> &messages);

  /**
   * @brief Updates weight texture if new weight has occured.
   *
   * Creates a new texture and sets the expected width and position of the new
   * weight.
   *
   * @param newWeight the new weight to present.
   */
  void updateWeightTexture(int newWeight);

  /**
   * @brief Updates time texture if new time has occured.
   *
   * Creates a new time texture of the updated time.
   * Position will always stay the same.
   *
   * @param timepoint measured by device.
   */
  void updateTimeTexture(std::string_view timepoint);

  /**
   * @brief update the timeString to present a new time
   */
  void updateTimestring();

  /**
   * @brief Steady clock timer
   *
   * @param milliSeconds
   * Amount of milliseconds until timer is finished.
   *
   * @return true when @param milliSeconds has passed.
   */
  bool timer(int milliSeconds);

  /**
   * @brief Function for determining if a weight update is needed.
   *
   * Saves the previous weight for comparing the incoming weight.
   *
   * @param weight incoming weight to compare.
   *
   * @returns
   * true - if incoming weight is not the same.
   * false - if weight is higher than MAX_WEIGHT.
   */
  bool checkWeight(int weight);

  /**
   * @brief Function for determining if a time update is needed
   *
   * Stores the previous time to compare the incoming time
   *
   * @param currentTimep incoming time generated by system
   *
   * @returns
   * true - if incoming weight is not the same
   * false - if no update is needed
   */
  bool checkTime(std::string_view currentTimepoint);

  /**
   * @brief State function to for handling evnet loop.
   *
   * @return True if event is found.
   */
  bool hasEvent() const;

  /**
   * @brief Pops previous and event a pushes next event forward.
   *
   * @return Next available event, or .empty().
   */
  SDL_Event getNext();

  /**
   * @brief Determine the background color of window.
   *
   * Clears previous window and set a new rendering color,
   * based on the amount of RGB and always set to ALPHA_OPAQUE.
   *
   * @param r amount of red.
   * @param g amount of green.
   * @param b amount of blue.
   */

  void setRenderingColor(Uint8 r, Uint8 g, Uint8 b);

  /**
   * @brief Standard specifics to determine position of textures.
   *
   * Represents where a certain texture will appear on the screen measured in
   * pixels.
   *
   * @param surface pointer used by window.
   * @param x cursor of textures top left corner.
   * @param y cursor of textures top left corner.
   * @param w width of texture.
   * @param h height of texture.
   */
  void setSurfacePosition(Graphics::SDLSurfaceSpec *surface, Uint16 x, Uint16 y,
                          Uint16 w, Uint16 h);

  /**
   * @brief
   * Configuarion for the positioning of messages.
   *
   * @param strings Reference to literals defined in setup()
   * @param vec reference to the SDLMessage configuration.
   */
  void setMessagePositionOf(const std::vector<std::string> &strings,
                            std::vector<Graphics::SDLMessage> &vec);

  /**
   * @brief The length of new incoming weight.
   *
   * Checks the length and returns the right amount for setting a new font
   * width.
   *
   * @param weight incoming weight.
   *
   * @return the width of new weight.
   */
  int checkLengthOfWeight(int weight);

  /**
   * @brief Sets the wanted width of weight texture.
   *
   * Sets a new width relative to the weight.
   * Called whenever current weight gets updated.
   *
   * @param weight
   * Depending of the size of the weight.
   */
  void setWeightWidth(int weight);

  // Raw pointers to SDL instances.

  SDL_Window *getRawWindow() const;
  SDL_Renderer *getRawRenderer() const;
  SDL_Surface *getRawSurface() const;
  SDL_Texture *getRawLogo() const;
  SDL_Texture *getRawTime() const;
  SDL_Texture *getRawImage() const;
  SDL_Texture *getRawWeight() const;
  SDL_Texture *getRawMessage(int index) const;
  TTF_Font *getRawFont() const;

  // Attributes

  /**
   * @brief The status of SDL Windows.
   *
   * Represents the state of the SDL Window. Set true when window is running,
   * and is set false when shutdown is requested.
   */
  bool status = true;

  /**
   * @brief
   *
   * true, presents a weight generated if set to false.
   */
  bool showWeight = false;

  /**
   * @brief
   * A boolean that is determined from the PinState of the Key Switch.
   */
  bool keyOverride = false;

  /// @brief Override and present weight when true
  bool successfulPayment = false;

  /// @brief Another bool to stop evaluating previous payment
  bool paymentReceived = false;

  Graphics::StateTimer weightTimer;
  Graphics::StateTimer paymentProcessTimer;
  Graphics::StateTimer messageTimer;

  /// @brief Another bool to stop evaluating previous payment
  bool paymentReceived = false;

  /**
   * @brief State of rendering, present welcome message first.
   */
  SurfaceState renderStates = SurfaceState::WELCOME_MESSAGE;

  int weightWidth = 0; // Width of font (dynamic during runtime).
  int weightX = 0;     // X cursor of font (dynamic during runtime).

  std::string timepoint; // Store the incoming timepoint

  Graphics::SDLSurfaceSpec
      logoSpec; // Specs for the logo presented (bottom right).
  Graphics::SDLSurfaceSpec
      timeSpec; // Specs for the time presented (bottom left).
  Graphics::SDLSurfaceSpec
      qrSpec; // Specs for the qr images presented (centered).
  Graphics::SDLSurfaceSpec
      weightSpec; // Specs for the weight presented (centered).

  std::vector<Graphics::SDLMessage> message; // Vector for multiple lines.
  Graphics::sdl_unique<SDL_Texture> logo; // Texture for logo (always visible).
  Graphics::sdl_unique<SDL_Texture>
      time; // Texture for timestamp (always visible)
  Graphics::sdl_unique<SDL_Texture> image;     // Texture for QR code.
  Graphics::sdl_unique<SDL_Texture> weight;    // Texture for weight.
  Graphics::sdl_unique<SDL_Surface> surface;   // Surface.
  Graphics::sdl_unique<TTF_Font> font;         // Font.
  Graphics::sdl_unique<SDL_Renderer> renderer; // Renderer.
  Graphics::sdl_unique<SDL_Window> window;     // Window.

  /**
   * @brief Event handler for dekstop application.
   *
   * Queue for handling events made on the SDL Application Window.
   * Only used on x86 build.
   */
  std::queue<SDL_Event> events;
  SDL_Event event; // Single event happening.
};

#endif